project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!draft_pages/"
    - "!back-end/"
    - "!_hold/"
    - "!_studies/"
#  pre-render: rm -f *\ *.html
  
format:
  html:
    theme: 
      light: [styles.scss, brand]
    mainfont: gandisans
    toc-location: right
    css: styles.css
    date: ""
    number-sections: true

website:
  title: "Shambhala Mirror Standards"
  description: "A set of standards for data reporting in the Shambhala Mirror."
  llms-txt: true
  favicon: "/images/SI-sunburst.ico"
  site-url: "https://smithjd.github.io/mirror-standards/"
  navbar:
    logo: "images/SI-sunburst.png"
    pinned: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Shambhala"
        href: "https://shambhala.org"
    tools: 
      - icon: github
        text: Github
        href: https://github.com
  page-navigation: true
  sidebar:
    contents:
      - section: "Societal Mirror Site Standards"
        contents:
          - text: Survey Page Standards
            href: survey-page-standards.qmd
          - text: Quarto File Standards
            href: quarto-file-standards.qmd
          - text: Admin Page Standards
            href: admin-page-standards.qmd
      - section: "Newsroom Data Reporting Standards"
        contents:
          - text: Newsroom Standards
            href: newsroom-data-reporting-standards/newsroom-standards.qmd
          - text: Principles
            href: newsroom-data-reporting-standards/01-principles.qmd
          - text: Chart Types
            href: newsroom-data-reporting-standards/02-chart-types.qmd
          - text: Color Palettes
            href: newsroom-data-reporting-standards/03-color-palettes.qmd
          - text: Typography Annotation
            href: newsroom-data-reporting-standards/04-typography-annotation.qmd
          - text: Accessibility
            href: newsroom-data-reporting-standards/05-accessibility.qmd
          - text: Implementation R
            href: newsroom-data-reporting-standards/06-implementation-r.qmd
          - text: Newsroom Sources
            href: newsroom-data-reporting-standards/07-sources.qmd
      - section: "Site metrics and analytics"
        contents:
          - text: Editing History
            href: editing_history.qmd
